mongohost: localhost
mongoport: 27017
mongodb: mydb

server:
  applicationConnectors:
    - type: https
      port: 8443
      keyStorePath: keystore.jks
      keyStorePassword: concurgdriveconnect
      validateCerts: false
